version: "2.2"
services:

  mysql:
    image: mysql:8.0.16
    container_name: metricbeat-mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
    networks:
      - mysql

networks:
  mysql:
    external:
      name: elk-lab
