# -*- mode: ruby -*-
# vi: set ft=ruby :

# README
#
# Getting Started:
# 1. vagrant plugin install vagrant-hostmanager
# 2. vagrant up
# 3. vagrant ssh
#
# This should put you at the control host
#  with access, by name, to other vms
Vagrant.configure(2) do |config|
  config.hostmanager.enabled = true

  config.vm.box = "centos/7"

  config.vm.define "orch", primary: true do |h|
    h.vm.hostname = "orch"
    h.vm.network "private_network", ip: "10.0.0.101"
    h.vm.provision :shell, path: "docker-install-script.sh"
  end

  config.vm.define "app1" do |h|
    h.vm.network "private_network", ip: "10.0.0.102"
    h.vm.hostname = "app1"
    h.vm.provision :shell, path: "docker-install-script.sh"
  end
end
